Repository mendoza-allendg/sea-bit, pull requests merged in 2024-01, with the labels that each got.

#1 Update README.md
  README.md
Labels: Heavenly Restriction

#7 Update README.md
  README.md
Labels: Heavenly Restriction

#9 NextJS Packages
  front/.eslintrc.json
  front/.gitignore
  front/README.md
  front/app/favicon.ico
  front/app/globals.css
  front/app/layout.tsx
  front/app/page.tsx
  front/next.config.js
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/public/next.svg
  front/public/vercel.svg
  front/tailwind.config.ts
  front/tsconfig.json
Labels: Domain Expansion

#13 add rspec
  .rspec
  Gemfile
  Gemfile.lock
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/test_helper.rb
Labels: Domain Expansion

#15 Added NextUI library
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/styles/favicon.ico
  frontend/styles/globals.css
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: Domain Expansion

#17 Added prettier
  frontend/.eslintrc.json
  frontend/.prettierrc
  frontend/layouts/default.tsx
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: Domain Expansion

#19 Add lint workflow
  .github/workflows/eslint.yml
Labels: Domain Expansion

#20 fixed workflow
  .github/workflows/eslint.yml
Labels: Heavenly Restriction

#26 Added pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Heavenly Restriction

#24 Created Header component
  README.md
  frontend/components/shared/header.tsx
  frontend/layouts/default.tsx
  frontend/package.json
  frontend/pages/index.tsx
  frontend/public/logo2.png
  frontend/public/logo3.png
  frontend/public/logo4.png
  frontend/public/logo5.png
  frontend/public/logo6.png
  frontend/public/output.css
  frontend/styles/globals.css
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: Domain Expansion

#27 updated readme
  README.md
Labels: Heavenly Restriction

#28 Change workflow trigger
  .github/workflows/eslint.yml
Labels: Heavenly Restriction

#29 Removed output.css from repo
  README.md
  frontend/package.json
  frontend/public/output.css
Labels: Heavenly Restriction

#31 improved search bar
  frontend/pages/index.tsx
Labels: Domain Expansion

#32 Devise auth
  Gemfile
  Gemfile.lock
  README.md
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/models/user.rb
  app/serializers/user_serializer.rb
  config/application.rb
  config/credentials.yml.enc
  config/environments/development.rb
  config/initializers/cors.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/puma.rb
  config/routes.rb
  db/migrate/20240119225415_devise_create_users.rb
  db/migrate/20240119231318_add_jti_to_users.rb
  db/schema.rb
  spec/models/user_spec.rb
Labels: Domain Expansion

#33 refactored eslintrc
  frontend/.eslintrc.json
  frontend/components/shared/Header.tsx
  frontend/layouts/default.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: Heavenly Restriction

#35 created authentication modal
  frontend/components/authentication/AuthButton.tsx
  frontend/components/shared/Header.tsx
  frontend/styles/globals.css
Labels: Domain Expansion

#36 initial changes for API connection
  frontend/apis/authentication/models.ts
  frontend/apis/authentication/useAuthentication.ts
  frontend/apis/hooks.ts
  frontend/components/authentication/AuthButton.tsx
  frontend/components/shared/Header.tsx
  frontend/components/utils/QueryProvider.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/index.tsx
  frontend/styles/globals.css
  frontend/yarn.lock
Labels: Domain Expansion

#34 created footer component | Footer Early Access
  frontend/components/shared/Footer.tsx
  frontend/layouts/default.tsx
  frontend/public/payment_logos/7_eleven.png
  frontend/public/payment_logos/7_eleven.png:Zone.Identifier
  frontend/public/payment_logos/AUB.png
  frontend/public/payment_logos/AUB.png:Zone.Identifier
  frontend/public/payment_logos/BPI.png
  frontend/public/payment_logos/BPI.png:Zone.Identifier
  frontend/public/payment_logos/BillEase.png
  frontend/public/payment_logos/BillEase.png:Zone.Identifier
  frontend/public/payment_logos/CebuanaLL.png
  frontend/public/payment_logos/CebuanaLL.png:Zone.Identifier
  frontend/public/payment_logos/CoinsPH.png
  frontend/public/payment_logos/CoinsPH.png:Zone.Identifier
  frontend/public/payment_logos/Gcash.png
  frontend/public/payment_logos/Gcash.png:Zone.Identifier
  frontend/public/payment_logos/GrabPay.png
  frontend/public/payment_logos/GrabPay.png:Zone.Identifier
  frontend/public/payment_logos/Landbank.jpg
  frontend/public/payment_logos/Landbank.jpg:Zone.Identifier
  frontend/public/payment_logos/M_LL.png
  frontend/public/payment_logos/M_LL.png:Zone.Identifier
  frontend/public/payment_logos/PayMaya.png
  frontend/public/payment_logos/PayMaya.png:Zone.Identifier
  frontend/public/payment_logos/SecurityBank.png
  frontend/public/payment_logos/SecurityBank.png:Zone.Identifier
  frontend/public/payment_logos/mastercard.png
  frontend/public/payment_logos/mastercard.png:Zone.Identifier
  frontend/public/payment_logos/visa.png
  frontend/public/payment_logos/visa.png:Zone.Identifier
Labels: Domain Expansion

#39 fix layout
  frontend/pages/index.tsx
Labels: Reverse Cursed Technique

#40 format tailwind classes
  frontend/.prettierrc
  frontend/components/authentication/AuthButton.tsx
  frontend/components/shared/Footer.tsx
  frontend/components/shared/Header.tsx
  frontend/layouts/default.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/index.tsx
  frontend/yarn.lock
Labels: Heavenly Restriction

#41 connected backend initial
  .github/workflows/eslint.yml
  app/controllers/users/registrations_controller.rb
  config/routes.rb
  frontend/apis/authentication/hooks.ts
  frontend/apis/authentication/useAuthentication.ts
  frontend/apis/common.ts
  frontend/apis/hooks.ts
  frontend/components/authentication/AuthButton.tsx
  frontend/package.json
  frontend/yarn.lock
Labels: Domain Expansion

#42 add react hook form
  frontend/.env.sample
  frontend/apis/authentication/hooks.ts
  frontend/components/authentication/AuthButton.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/yarn.lock
Labels: Domain Expansion

#43 implemented orval initial
  README.md
  frontend/apis/authentication/endpoints/RegistrationsApi.ts
  frontend/apis/authentication/models.ts
  frontend/apis/authentication/models/errorDTO.ts
  frontend/apis/authentication/models/index.ts
  frontend/apis/authentication/models/userDTO.ts
  frontend/apis/authentication/models/userRegistrationParams.ts
  frontend/components/authentication/AuthButton.tsx
  frontend/orval.config.ts
  frontend/orval/api/authentication/registration.yaml
  frontend/package.json
  frontend/yarn.lock
Labels: Domain Expansion
